In [1]:
#Write a Python program to check if a number is prime.
def is_prime(n):
    if n==2:
        return True
    else:
        for i in range(2,n-1):
            if(n%i==0):
                return False
    return True

n=int(input("Enter the number you want to check if its a prime : "))
print(is_prime(n))


False


In [11]:
#Create a Fibonacci sequence generator using recursion
def fibonacci(n,m,size):
    if(size>0):
        print(m,end=" ")
        fibonacci(m,m+n,size-1)
    else:
        return 0;

size=int(input("Enter the size : "))
print(1,end=" ")
fibonacci(1,2,size-1)

    

Enter the size :  20


1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 

In [15]:
#Write a function to find the Greatest Common Divisor (GCD) and Least Common Multiple (LCM) of two numbers
def gcd(n,m):
    if n>m:
        if n%m==0:
            return m;
        else:
            gcdn=0;
            for i in range(m):
                if n%i==0 and m%i==0:
                    gcdn=i
            return gcdn
    elif n==m:
        return n
    else:
        if m%n==0:
            return n;
        else:
            gcdn=0;
            for i in range(n):
                if n%i==0 and m%i==0:
                    gcdn=i
            return gcdn

def lcm(n,m):
    lcmn=(n*m)/gcd(n,m)
    return lcmn

n=int(input("Enter no 1 : "))
m=int(input("Enter no 2 : "))
print(f"GCD is {gcd(n,m)}")
print(f"LCM is {lcm(n,m)}")
    
        
        

Enter no 1 :  10
Enter no 2 :  20


GCD is 10
LCM is 20.0


In [2]:
#Build a simple calculator using functions.
def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
a=int(input("Enter no 1 : "))
b=int(input("Enter no 2: "))
print("Addition is :",add(a,b))
print("Subtraction is :",sub(a,b))
print("Multiplication is :",mul(a,b))
print("Division is :",div(a,b))

Addition is : 30
Subtraction is : -10
Multiplication is : 200
Division is : 0.5


In [4]:
#Implement a program that takes a list and removes duplicates
list1=[10,20,30,10,20,30,30]
print("List before removing duplicates is :",list1)
set1=set(list1)
print("List after deleting duplicates is :",list(set1))

List before removing duplicates is : [10, 20, 30, 10, 20, 30, 30]
List after deleting duplicates is : [10, 20, 30]


In [6]:
#Create a dictionary, add five key-value pairs, and print them
dict1={"a":1,"b":2,"c":3,"d":4,"e":5}
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [12]:
#Use NumPy to perform basic matrix operations.
import numpy as np
matrix1=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
matrix2=np.array([[9,8,7],
        [6,5,4],
        [3,2,1]])
print("Matrix addition is :\n",matrix1+matrix2)
print("Matrix subtraction is :\n",matrix1-matrix2)
print("Matrix multiplication is :\n",matrix1*matrix2)
print("Matrix division is :\n",matrix1/matrix2)

Matrix addition is :
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix subtraction is :
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix multiplication is :
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix division is :
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [17]:
#Read a CSV file using pandas and display the first 5 rows.
import pandas as pd
file1=pd.read_csv("C:/Users/pagil/OneDrive/Documents/Datasets/car sales data  set/Car Sales India 2024.csv")
df=pd.DataFrame(file1)
print(df.head())

      Make        Model January February March April  May June July August  \
0  Citroen       Basalt       0        0     0     0    0    0    0    579   
1  Citroen           C3     234      211   265   251  155   77   90    507   
2  Citroen     Aircross     231      127   211    93  125  136   68     38   
3  Citroen  C5 Aircross       1        0     0     1    0    0    0      1   
4  Citroen         e-C3     184       83   530    59  235  126  177    150   

   ... October  November  December   Total  Segment  Body Type MoM %  YoY %  \
0  ...      221        47       79  1267.0       C2        SUV  68.0    0.0   
1  ...      300       200      300  2890.0       C1  Hatchback  50.0   -3.0   
2  ...      103       201       96  1470.0       C2        SUV -52.0  -72.0   
3  ...        4         0        1     9.0       D2        SUV   0.0  -50.0   
4  ...       89        61       90  1812.0       C1        SUV  48.0    0.0   

   Unnamed: 19  Unnamed: 20  
0          NaN          Na

In [ ]:
#Write a function that finds the most common word in a given text.
def most_common_word(text):
    text = text.lower()
    words = text.split()
    word_counts = {}
    for word in words:
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1
    
    most_common = max(word_counts, key=word_counts.get)
    
    return most_common

text = "This this this what is this"
print(most_common_word(text))


this


In [21]:
#Create a function that generates a random password with a mix of uppercase, lowercase, digits, and special characters.
import random
import string

def generate_random_password(length):
    uppercase_letters = string.ascii_uppercase
    lowercase_letters = string.ascii_lowercase
    digits = string.digits
    special_characters = string.punctuation
    password = [
        random.choice(uppercase_letters),
        random.choice(lowercase_letters),
        random.choice(digits),
        random.choice(special_characters)
    ]
    all_characters = uppercase_letters + lowercase_letters + digits + special_characters
    password += random.choices(all_characters, k=length - 4)
    random.shuffle(password)
    return ''.join(password)
password_length = 12
print(generate_random_password(password_length))


l#Xnn[H(sS0E
